/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './*.html',
    './**/*.html',
    './assets/**/*.js',
    '!./node_modules/**',
    '!./perf/**'
  ],
  theme: {
    extend: {
      fontFamily: {
        serif: ['"Cormorant Garamond"', '"Playfair Display"', 'Georgia', 'serif'],
        sans: ['"Montserrat"', '"Plus Jakarta Sans"', '"Inter"', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', '"Liberation Mono"', '"Courier New"', 'monospace'],
        display: ['"Cormorant Garamond"', '"Playfair Display"', '"Arial Black"', 'Georgia', 'serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Playfair Display"', 'serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-caps-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-lg': ['"Playfair Display"', 'serif'],
        'headline-sm': ['"Playfair Display"', 'serif'],
        'title-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'data-mono': ['"Plus Jakarta Sans"', 'monospace'],
        'headline-lg-mobile': ['"Playfair Display"', 'serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'label-caps-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-lg-mobile': ['"Playfair Display"', 'serif']
      },
      colors: {
        'secondary-container': '#fea277',
        'on-tertiary-container': '#997f61',
        'on-secondary-fixed-variant': '#743412',
        'primary-container': '#1d1b1a',
        'tertiary-fixed': '#fdddb9',
        'on-secondary': '#ffffff',
        'surface-dim': '#dfd9d5',
        'on-tertiary-fixed': '#281803',
        'inverse-surface': '#32302e',
        'on-background': '#1d1b19',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#fff8f4',
        'outline': '#7c766f',
        'tertiary': '#000000',
        'on-primary-fixed': '#1d1b1a',
        'secondary-fixed-dim': '#ffb694',
        'on-secondary-container': '#773614',
        'primary-fixed-dim': '#cac6c3',
        'inverse-primary': '#cac6c3',
        'tertiary-fixed-dim': '#e0c29f',
        'primary-fixed': '#e6e1df',
        'surface-bright': '#fff8f4',
        'secondary-fixed': '#ffdbcc',
        'on-primary': '#ffffff',
        'error': '#ba1a1a',
        'on-secondary-fixed': '#351000',
        'outline-variant': '#cdc5bd',
        'on-primary-container': '#868381',
        'surface-container-highest': '#e7e1de',
        'on-tertiary-fixed-variant': '#584329',
        'surface-tint': '#605e5c',
        'secondary': '#924b27',
        'on-primary-fixed-variant': '#484645',
        'on-surface': '#1d1b19',
        'on-surface-variant': '#4b4640',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f9f2ee',
        'on-error': '#ffffff',
        'surface-container': '#f3ede9',
        'background': '#fff8f4',
        'primary': '#000000',
        'inverse-on-surface': '#f6efec',
        'surface-variant': '#e7e1de',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#ede7e3',
        'tertiary-container': '#281803',
        'rh-sale': '#8c2826',
        'rh-muted': '#a39b90',
        'rh-gold': '#d1c7b7',
        'pageBg': '#F7F5F0',
        'brandRed': '#E24A3B',
        'linen': '#F8F6F2',
        'linen-card': '#FAF8F5',
        'taupe-banner': '#73685B',
        'cream-bg': '#F6F5F2',
        'charcoal-text': '#1D1D1D',
        'muted-address': '#686663',
        'track-bg': '#E4E2DC',
        brand: {
          DEFAULT: '#1A1A1A',
          bg: '#F6F4EE',
          hero: '#7D786D',
          text: '#2B2927',
          muted: '#65625D',
          border: '#2B2927',
          accent: '#E6492D',
          black: '#0D0C0B',
          dark: '#161513',
          charcoal: '#242220',
          cream: '#F9F8F5',
          sand: '#F2EFE9',
          stone: '#E6E2D8',
          clay: '#8C7D70',
          rust: '#C25E3E',
          whatsapp: '#25D366',
          warmgray: '#E6E2D8',
          taupe: '#786F63'
        }
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ]
};
